### ISSUE TITLE
Dynamically add widgets to dashboard

### ISSUE THREAD

**Issue by ddewaele** [edfungus/Crouton#17]
Hi,

Thx a lot for creating this cool project....

Had a small question on updating an existing dashboard.
Is there a way to add cards to an existing device dashboard ? (without re-creating the device via the `/outbox/"+clientName+"/deviceInfo` topic ?

**Comment by edfungus** [comment]
If I remember correctly, if the device sends another deviceInfo, it should update the cards shown (I think I added this feature....) If not, a disconnect and reconnect of the device with the new card entries in the deviceInfo will create the new cards.

Right now there is no way to add cards from the interface. Since the device needs to also be configured to know which cards to send values to, the card declarations, as of now, are all done on the device's json side.
